apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  annotations:
    epinio.suse.org/registry-namespace: {{ .Values.registry.namespace }}
    kubed.appscode.com/sync: kubed-sync=registry-creds
  name: registry-creds
  namespace: epinio-staging
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ .Values.registry.url }}": {
          "auth":"{{ printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc }}",
          "username":"{{ .Values.registry.username }}",
          "password":"{{ .Values.registry.password }}"
        } {{- if and .Values.registry.localhostURL (not .Values.registry.externalRegistryURL) }} ,
        "{{ .Values.registry.localhostURL }}": {
          "auth":"{{ printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc }}",
          "username":"{{ .Values.registry.username }}",
          "password":"{{ .Values.registry.password }}"
        }
        {{- end -}}
      }
    }
